# -*- mode: ruby -*-
# vi: set ft=ruby :

## This virtual machine only for doing the intialization job

$script = <<SCRIPT
   #set timezone
   sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 
   source_tmp=163
   #source_tmp=aliyun
   #set source
   sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak 
   sudo echo "deb http://mirrors.${source_tmp}.com/debian/ jessie main non-free contrib" > /etc/apt/sources.list \
   && sudo echo "deb http://mirrors.${source_tmp}.com/debian/ jessie-updates main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb http://mirrors.${source_tmp}.com/debian/ jessie-backports main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb http://mirrors.${source_tmp}.com/debian-security/ jessie/updates main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb-src http://mirrors.${source_tmp}.com/debian/ jessie main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb-src http://mirrors.${source_tmp}.com/debian/ jessie-updates main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb-src http://mirrors.${source_tmp}.com/debian/ jessie-backports main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb-src http://mirrors.${source_tmp}.com/debian-security/ jessie/updates main non-free contrib" >> /etc/apt/sources.list 
   sudo apt-get update
   sudo apt-get -y install build-essential python-setuptools python-dev vim ntpdate bridge-utils sshpass
   sudo easy_install -i http://pypi.douban.com/simple/ pip
   
   #install ansible 2.2.0.0
   mkdir ~/.pip
   echo "[global]" > ~/.pip/pip.conf \
   && echo "index-url = http://pypi.douban.com/simple" >> ~/.pip/pip.conf \
   && echo "trusted-host = pypi.douban.com" >> ~/.pip/pip.conf  
   sudo mkdir -p /root/.pip && sudo cp pip.conf /root/.pip/
   sudo pip install ansible==2.2.0.0 -i http://pypi.douban.com/simple/  --trusted-host pypi.douban.com
   
   #sync sshkey
   #mkdir -p /home/vagrant/.ssh && cp /vagrant/test/id_rsa  /home/vagrant/.ssh/id_rsa && sudo chmod 600 /home/vagrant/.ssh/id_rsa
   #ln -s /vagrant/InitializeHosts /home/vagrant/IntializeHosts

SCRIPT


nodes = {
    'nim-initializer' => [1, 110],
}

Vagrant.configure("2") do |config|
    #config.vm.box = "debian8"
    config.vm.box = "debian/jessie64"
    config.vm.box_check_update = false
    config.vm.synced_folder "../", "/vagrant", type: "virtualbox"
    nodes.each do |prefix, (count, ip_start)|
        count.times do |i|
            hostname = "%s-%02d" % [prefix, (i+1)]
            
            config.vm.provider "virtualbox" do |vb|
                vb.memory = "1024"
                vb.cpus = 2
            end
            config.vm.define "#{hostname}" do |box|
                puts "working on #{hostname} with ip of 192.168.200.#{ip_start+i}"
                box.vm.hostname = "#{hostname}"
                box.vm.network :private_network, :ip => "192.168.200.#{ip_start+i}", :netmask => "255.255.255.0"
            end
            config.vm.provision "shell", inline: $script
        end
    end
end
