# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
   
   #set timezone
   sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime 
   
   #set source
   sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak 
   sudo echo "deb http://mirrors.aliyun.com/debian/ jessie main non-free contrib" > /etc/apt/sources.list \
   && sudo echo "deb http://mirrors.aliyun.com/debian/ jessie-updates main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb http://mirrors.aliyun.com/debian/ jessie-backports main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb http://mirrors.aliyun.com/debian-security/ jessie/updates main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb-src http://mirrors.aliyun.com/debian/ jessie main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb-src http://mirrors.aliyun.com/debian/ jessie-updates main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb-src http://mirrors.aliyun.com/debian/ jessie-backports main non-free contrib" >> /etc/apt/sources.list \
   && sudo echo "deb-src http://mirrors.aliyun.com/debian-security/ jessie/updates main non-free contrib" >> /etc/apt/sources.list 
   sudo apt-get update
   sudo apt-get -y install build-essential python-setuptools python-dev
   sudo easy_install -i http://pypi.douban.com/simple/ pip
   
   #install ansible 2.2.0.0
   mkdir ~/.pip
   echo "[global]" > ~/.pip/pip.conf \
   && echo "index-url = http://pypi.douban.com/simple" >> ~/.pip/pip.conf \
   && echo "trusted-host = pypi.douban.com" >> ~/.pip/pip.conf  
   sudo mkdir /root/.pip && sudo cp pip.conf /root/.pip/
   sudo pip install ansible==2.2.0.0 -i http://pypi.douban.com/simple/  --trusted-host pypi.douban.com
   
   #install basic util
   sudo apt-get update
   sudo apt-get -y install vim ntpdate bridge-utils sshpass openjdk-7-jdk ant maven tree

   #install docker software and set mirror 
   sudo apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
   curl -fsSL https://download.daocloud.io/docker/linux/debian/gpg | sudo apt-key add -
   sudo add-apt-repository \
   	"deb [arch=$(dpkg --print-architecture)] https://download.daocloud.io/docker/linux/debian \
   	$(lsb_release -cs) stable"
   sudo apt-get update
   sudo apt-get install -y -q docker-ce=17.03.2*
   sudo service docker start
   sudo service docker status
   curl -sSL https://get.daocloud.io/daotools/set_mirror.sh | sudo sh -s http://e0709a75.m.daocloud.io
   sudo service docker restart

   echo -e "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64" >> /home/vagrant/.bashrc
SCRIPT


nodes = {
    'nim-build' => [1, 10],
}

Vagrant.configure("2") do |config|

    #config.vm.box = "debian8"
    config.vm.box = "debian/jessie64"
    config.vm.box_check_update = false
    config.vm.synced_folder "../", "/vagrant", type: "virtualbox"
    nodes.each do |prefix, (count, ip_start)|
        count.times do |i|
            hostname = "%s-%02d" % [prefix, (i+1)]
            
            config.vm.provider "virtualbox" do |vb|
                vb.memory = "2048"
                vb.cpus = 2
            end

            config.vm.define "#{hostname}" do |box|
                puts "working on #{hostname} with ip of 192.168.200.#{ip_start+i}"
                box.vm.hostname = "#{hostname}"
                box.vm.network :private_network, :ip => "192.168.200.#{ip_start+i}", :netmask => "255.255.255.0"
            end
            config.vm.provision "shell", inline: $script
        end
    end
end
